### PR TITLE
Use kitchen logger to keep log files and color output

### PR DESCRIPTION
**Pull request by benLogN**
Cool project! I saw Issue #3 and figured it was a good place to take a look around in a kitchen driver. The changes are, in order:
* Make it so the logger gets passed through
* Turn off coloring on the provisioner
* Use the logger append instead of print.

### CODE REVIEW

**Comment by someara** [comment]
sweet, thanks!
-s

**Comment by someara** [comment]
reverting this for now... it's causing garbled output on Travis:

https://travis-ci.org/someara/etcd-cookbook/jobs/99462226

I wonder what's causing all those extra line breaks

**Comment by benLogN** [comment]
Hmm, interesting. I know what's causing some of the line breaks (https://github.com/someara/kitchen-dokken/pull/5/files#diff-e50af27eed3b0cc25806cd3c08774f5fR85), but I put in this newline because without this, adjacent lines were ending up printing on the same line (i.e. all of the resources would end up stacked on the same line, aside from the newlines in the file diffs). I can dig back into this in a day or two.

**Comment by someara** [comment]
Thanks Benjamin!

**Pull request merged**
